### ISSUE TITLE
Request for information

### ISSUE THREAD

**Issue by sai43** [marks/truevault.rb#13]
Hi marks,

I am using truevault for my sample application, it is very nice. But I am confused with Rest Calls provided by truevault, like 

curl https://api.truevault.com/v1/vaults/00000000-0000-0000-0000-000000000000/blobs \
    -X POST \
    -u [API_KEY | ACCESS_TOKEN]: \
    --form "file=@xray.pdf" \
    -H "Content-Type:multipart/form-data"

I've not understand to use "file" in with post data i am try this curl command in console.
Then I am getting missing global parameter 'file' with 400 BAD Request.

please suggest me

**Comment by marks** [comment]
Hi @sai43 - is this question regarding this (admittedly unmaintained, mostly due to a job change of mine and no longer needing a secure HIPAA store) gem/library or straight up REST calls for Truevault?

If the latter, you are much better off contacting them directly

**Comment by sai43** [comment]
I got success response. No Problem
